title: <p align="center"> Thien Kim To </p>

logo: "/images/image_profile-01.png?raw=true"

description:
  <p align="center">
  <a href="pdf/CV_ToThienKim">CV</a> |
  <a href="https://www.linkedin.com/in/thienkimto/">LinkedIn</a> |
  <a href="https://github.com/thienkim-to">GitHub</a>
  </p>
  
  <p align="justify">
  As a 3rd year student who loves working with data. Passionate about studying how to improve performance. 
  Seeking to leverage data analytical skills to improve corporate performance as a data analyst
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID
