title: <p align="center"> Thien Kim To </p>

logo: "/images/image_profile-01.png?raw=true"

description:
  <p align="center">
  <a href="pdf/CV_ToThienKim">CV</a> |
  <a href="https://www.linkedin.com/in/thienkimto/">LinkedIn</a> |
  <a href="https://github.com/thienkim-to">GitHub</a>
  </p>
  
  <p align="justify">
  I am a third-year student majoring in E-commerce at the University of Economics and Law.</br>
  My studies have provided me with broad proficiency in the use of data analysis methods, tools, software packages, and techniques. During that period of time, I aware that I am really interested in working with data. I want to know what the problems happened based on data and find the solutions to improve performance.</br>
  I have experience working with data in Excel, SQL, Power BI, and Python. I will continue to learn and practice so that I can master these skills. Currently, I hope to have an internship in Data Analysis that will provide real-life experience and important technological skills.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID
